### ISSUE TITLE
Start event of http server not being set or being set too late

### ISSUE THREAD

**Issue by maximilianpilz** [Draegerwerk/sdc11073#142]
The following error occurrs quite frequently under load:

> ... - sdc.device - ERROR - Cannot start device, start event of http server not set.
Traceback (most recent call last):
  File "venv\lib\site-packages\sdc11073\sdcdevice\sdcdeviceimpl.py", line 94, in startAll
    return self._handler.startAll(startRealtimeSampleLoop, periodic_reports_interval, shared_http_server)
  File "venv\lib\site-packages\sdc11073\sdcdevice\sdc_handlers.py", line 309, in startAll
    self._startServices(shared_http_server)
  File "venv\lib\site-packages\sdc11073\sdcdevice\sdc_handlers.py", line 274, in _startServices
    raise RuntimeError('Cannot start device, start event of http server not set.')
RuntimeError: Cannot start device, start event of http server not set.

Fix it or provide a way of configuring the timeout that is being applied when waiting for started_evt.

Found in version 1.1.22

**Comment by leon1995** [comment]
make timeout in [event_is_set = self._httpServerThread.started_evt.wait(timeout=15.0)](https://github.com/Draegerwerk/sdc11073/blob/185090bc2ba3e5ddff85df7ccbf90d8ac18359bf/src/sdc11073/sdcdevice/sdc_handlers.py#L271) configurable
