### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'shutdown'" in sdc11073.sdcclient.subscription

### ISSUE THREAD

**Issue by maximilianpilz** [Draegerwerk/sdc11073#145]
The following error occurred in sdc11073.sdcclient.subscription .

>   File "venv/lib/python3.10/site-packages/sdc11073/sdcclient/sdcclientimpl.py", line 414, in stopAll
    self._stopEventSink(closeAllConnections)
  File "venv/lib/python3.10/site-packages/sdc11073/sdcclient/sdcclientimpl.py", line 535, in _stopEventSink
    self._notificationsDispatcherThread.stop(closeAllConnections)
  File "venv/lib/python3.10/site-packages/sdc11073/sdcclient/subscription.py", line 643, in stop
    self.httpd.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'

Found in version 1.1.22

**Comment by a-kleinf** [comment]
consequential error of #142
