### ISSUE TITLE
BindingMdibVersion and BindingStartTime for newly created ContextState is not correct

### ISSUE THREAD

**Issue by a-kleinf** [Draegerwerk/sdc11073#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the `class _MdibUpdateTransaction` has the method `def getContextState` which creates a new ContextState having @ContextAssociation = "No". It then also sets the @BindingMdibVersion using the actual MDIB-version.
If this method is called during a transaction the MDIB version is increment at the end of the transaction. This leads to a  @BindingMdibVersion which is smaller than the MDIB-Version of the AbstractContextReport.

Also it is not expected that the @BindingMdibVersion and @BindingStartTime is set for a ContextState which has @ContextAssociation = "No".

### Expected Behavior

@BindingMdibVersion and @BindingStartTime are not set for a newly created ContextState which has @ContextAssociation = "No".

or

The @BindingMdibVersion is equal to the MDIB-version of the AbstractContextReport

### Minimal Reproducible Example

def test_episodicContextReportEvent(self)
could be used

### Python Version

3.9

### Operating system

Windows

### Sdc11073 Version

1.1.25

### Participation

- [X] I am willing to submit a pull request to fix this bug.

**Comment by leon1995** [comment]
has been fixed for v2 in #193

**Comment by a-kleinf** [comment]
further adaptions for v2 are needed
