### ISSUE TITLE
Editing Tutorial code to show transfer of dynamic data.

### ISSUE THREAD

**Issue by hhleroy97** [Draegerwerk/sdc11073#18]
Hi! I am interested in using this repo to demonstrate transfer of data from a medical device (i.e. a pacemaker), however I noticed that the tutorial code only updates the 'consumer' with a state change that increments consistently. If you could point me in the direction of how to alter the tutorial so that it displays actual data sent from the 'provider' it would be greatly appreciated!

Also in line 62 of provider.py I noticed that with the refactored code the 
`sdcDevice = sdc11073.sdcdevice.sdcdeviceimpl.PublishingSdcDevice(...)`
should be changed to
`sdcDevice = sdc11073.sdcdevice.sdcdeviceimpl.SdcDevice(...)`
Without the correction a 'module not found' error is thrown

**Comment by deichmab-draeger** [comment]
Hi! You only need to extend the onMetricUpdate function. In the tutorial it only prints the handles of updated metrics, but the parameter "metricsByHandle" is a dictionary with key=handle, value=updated object.

**Comment by hhleroy97** [comment]
Hi! Thanks for the advice! I was able to output the updated value in the base data format (i.e. or type int or string and not NumericStateContainer) by using the following line:

`print("Updated value = "+str(metricsByHandle[oneHandle]._MetricValue.Value))`

However, if I'm not mistaken the '_MetricValue' is somewhat improper to call, right? If so is there a better way to access the base data format?

**Comment by deichmab-draeger** [comment]
yes, there is a "metricValue" property. Please be aware that metricValue can be None, so metricValue.Value will raise an Exception in that case.
