### ISSUE TITLE
ext_Extension (containerproperties.ExtensionNodeProperty) comparison is not as expected

### ISSUE THREAD

**Issue by a-kleinf** [Draegerwerk/sdc11073#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The comparison of ext_Extension (instance of etree.Element) is not as expected.

When comparing two different instances of etree.Element the included data is not compared but it is checked that both instances are the same object.
This leads to a wrong comparison of ext_Extension attributes.

### Expected Behavior

When comparing two different instances of ext_Extension attributes, the included data shall be evaluated.

### Minimal Reproducible Example

```python
from lxml import etree
from sdc11073.definitions_sdc import SDC_v1_Definitions
from sdc11073 import pmtypes

ident_xml = b"""
<pm:Identification xmlns:pm="http://standards.ieee.org/downloads/11073/11073-10207-2017/participant"
                   Root="urn:uuid:90beab82-f160-4e2f-b3b2-ed8cfcf5e205"
                   Extension="123.234.424">
    <ext:Extension xmlns:ext="http://standards.ieee.org/downloads/11073/11073-10207-2017/extension">
        <foo someattr="somevalue"/>
        <bar anotherattr="differentvalue"/>
    </ext:Extension>
</pm:Identification>
"""
ident_xml_normalized = SDC_v1_Definitions.normalizeXMLText(ident_xml)
inst1 = pmtypes.InstanceIdentifier.fromNode(etree.fromstring(ident_xml_normalized))
inst2 = pmtypes.InstanceIdentifier.fromNode(etree.fromstring(ident_xml_normalized))

print(f"{inst1.ext_Extension == inst1.ext_Extension = }")
print(f"{inst2.ext_Extension == inst2.ext_Extension = }")

print(f"{inst1.ext_Extension == inst2.ext_Extension = } ????????? NOT EXPECTED ?????????")
print(f"{etree.tostring(inst1.ext_Extension) == etree.tostring(inst2.ext_Extension) = } !!!!!!!!")

print("Extension 1: " + str(etree.tostring(inst1.ext_Extension)))
print("Extension 2: " + str(etree.tostring(inst2.ext_Extension)))
```

OUTPUT:

inst1.ext_Extension == inst1.ext_Extension = True
inst2.ext_Extension == inst2.ext_Extension = True

inst1.ext_Extension == inst2.ext_Extension = False ????????? NOT EXPECTED ?????????
etree.tostring(inst1.ext_Extension) == etree.tostring(inst2.ext_Extension) = True !!!!!!!!

Extension 1: b'<ext:Extension xmlns:ext="__ExtensionPoint__" xmlns:pm="__BICEPS_ParticipantModel__">\n        <foo someattr="somevalue"/>\n        <bar anotherattr="differentvalue"/>\n    </ext:Extension>\n'
Extension 2: b'<ext:Extension xmlns:ext="__ExtensionPoint__" xmlns:pm="__BICEPS_ParticipantModel__">\n        <foo someattr="somevalue"/>\n        <bar anotherattr="differentvalue"/>\n    </ext:Extension>\n'

### Python Version

3.9

### Operating system

Windows

### Sdc11073 Version

1.1.28

### Participation

- [ ] I am willing to submit a pull request to fix this bug.

**Comment by a-kleinf** [comment]
similar bug was reported for the xml python library: https://bugs.python.org/issue37792

**Comment by leon1995** [comment]
this also affects version 2

**Comment by leon1995** [comment]
> similar bug was reported for the xml python library: https://bugs.python.org/issue37792

yeah, this is a problem in `lxml`, as
```python
etree.fromstring(ident_xml) == etree.fromstring(ident_xml)
```
also returns `False`

**Comment by leon1995** [comment]
requires fix for v1
