### ISSUE TITLE
bug: `isConnected` may be missleading

### ISSUE THREAD

**Issue by leon1995** [Draegerwerk/sdc11073#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/Draegerwerk/sdc11073/blob/3f80fd79be88b4e65b033ef10edb604d6090b5aa/src/sdc11073/sdcclient/subscription.py#L388
if there are no subscriptions, there are also no that are `not_okay`. This means, that the implication made at
https://github.com/Draegerwerk/sdc11073/blob/3f80fd79be88b4e65b033ef10edb604d6090b5aa/src/sdc11073/sdcclient/sdcclientimpl.py#L424
is not correct. It should also be checked, that there is at least one subscription.

### Expected Behavior

`isConnected` should be `True` if there is at least one subscription that is "okay"

### Python Version

3.9

### Operating system

windows

### Sdc11073 Version

1.3.0

### Participation

- [ ] I am willing to submit a pull request to fix this bug.

**Comment by leon1995** [comment]
`isConnected` should be renamed. Fix will be done in v2 only

**Comment by deichmab-draeger** [comment]
I think the logic for isConnected should be different: It is True if there is at least one subscription, and all subscriptions are okay.
