### ISSUE TITLE
bug: patient context state is not initiated properly by definitions base

### ISSUE THREAD

**Issue by Jevgenijus** [Draegerwerk/sdc11073#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When operation for PatientContext is initiated a Operation Target state container is created but
this initiation method is not handling context states correctly.
Cannot access the context state via regular api methods like
 mgr.get_context_state(state)

![image](https://github.com/Draegerwerk/sdc11073/assets/4412622/b75f198f-01df-433c-9fea-491db6c1eecc)

### Expected Behavior

PatientContext state is correctly created and available in the mdib.states index

### Python Version

3.9

### Operating system

Windows

### Sdc11073 Version

2.0.0a5

### Participation

- [X] I am willing to submit a pull request to fix this bug.

**Comment by deichmab-draeger** [comment]
Already fixed in version 2.0.0a6
