### ISSUE TITLE
Start of event sink fails on PC with multiple (similar) network adapters

### ISSUE THREAD

**Issue by AlexBue1993** [Draegerwerk/sdc11073#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On one PC with multiple network adapters (bluetooth, ethernet 1 and so on) the SDC Client start fails during start of the event sink:
`File ".venv\lib\site-packages\sdc11073\sdcclient\sdcclientimpl.py", line 368, in startAll
    self._startEventSink(async_dispatch, dispatcher_timeout=dispatcher_timeout)
  File ".venv\lib\site-packages\sdc11073\sdcclient\sdcclientimpl.py", line 552, in _startEventSink
    raise RuntimeError('Cannot start consumer, start event of EventSink not set.')
RuntimeError: Cannot start consumer, start event of EventSink not set.`

When disabling all network adapters except the one, where the SDC device is connected to, the SDC client can be started.

### Expected Behavior

SDC client starts and connects successfully independently of the number of PC network adapters.

### Python Version

3.8.10

### Operating system

win32

### Sdc11073 Version

1.3.0

### Participation

- [ ] I am willing to submit a pull request to fix this bug.

**Comment by leon1995** [comment]
could you please provide more details like logs, etc...

**Comment by AlexBue1993** [comment]
I once solved it by disabling a network adapter. Unfortunately, I could not reproduce it, yet. And I have no logs.
If it occurs once again, I will provide some logs.

**Comment by leon1995** [comment]
okay. I close the issue than. You can repoen it once it happens again
