### ISSUE TITLE
Write unittest to test method "ConsumerMdib.reload_all()"

### ISSUE THREAD

**Issue by a-kleinf** [Draegerwerk/sdc11073#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature idea

After a change of the Mdib SequenceId the "ConsumerMdib" (in consumermdib.py) will not update any received data.
An application using "class ConsumerMdib" has to call reload_all() to "reactivate" the processing of received reports.

reload_all() is not tested yet.

Write unittest to test reload_all after e.g. a SequenceId change. Verify that received reports are processed and other functionality is preserved (e.g. )
        self._is_initialized == True
        self._sequence_id_changed_flag == False
        observable properties are working
        MDIB version is as expected

### Alternatives

-

### Participation

- [ ] I am willing to submit a pull request to implement this feature.

**Comment by deichmab-draeger** [comment]
After a change of the sequence id it is unclear if the provider stopped sending notifications. In the reload phase the consumer should check if the existing subscriptions are still alive by sending renew or getstatus reequests and subscribe again if neccessary.
