### ISSUE TITLE
feature: make commlog.DirectoryLogger not write each message to a separate file

### ISSUE THREAD

**Issue by antipovi-draeger** [Draegerwerk/sdc11073#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature idea

the current implementation of the commlog.DirectoryLogger is not that user friendly since every message produces a separate log file. it would be better to have a log written to one file or a perhaps even a database

### Alternatives

no

### Participation

- [ ] I am willing to submit a pull request to implement this feature.

**Comment by a-kleinf** [comment]
the amount of created files may be very high. the OS might not be able to handle this.

**Comment by leon1995** [comment]
this is already possible in v2. dont use the commlogger but rather use your own handler.

e.g. if you want to add a handler to a specific logger like the `commlog.MULTICAST_OUT` logger, then
```python
logging.getLogger(commlog.MULTICAST_OUT).addHandler(your_handler)
```
