### ISSUE TITLE
bug: update xml node for descriptor in consumer mdib

### ISSUE THREAD

**Issue by Jevgenijus** [Draegerwerk/sdc11073#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when descriptor is updated on the provider side the consumer descriptor container is updated 
but its node property is not.

### Expected Behavior

 Consumer node property should also be updated for descriptor container

### Python Version

3.9.6

### Operating system

any

### Sdc11073 Version

2.0.1

### Participation

- [ ] I am willing to submit a pull request to fix this bug.

**Comment by deichmab-draeger** [comment]
fixed on master
