### ISSUE TITLE
Unknown Subscription ID when renewing a subscription with sdcX

### ISSUE THREAD

**Issue by DominikST95** [Draegerwerk/sdc11073#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The connection between sdcX (Consumer) and SDC11073 (Provider) is established normally. 
When renewing the subscription to the BICEPS service (independent of mode, error occurs both with path dispatching as well as reference parameters), sdc11073 will respond with a SOAP Fault. The subscription to the Set Service can be renewed in both cases. 
Example messages for all cases attached. 
[Out_NoRefParam.txt](https://github.com/user-attachments/files/15951241/Out_NoRefParam.txt)
[SDC11073_Set_RefParamOFF.txt](https://github.com/user-attachments/files/15951242/SDC11073_Set_RefParamOFF.txt)
[SDC11073_Set_RefParamON.txt](https://github.com/user-attachments/files/15951243/SDC11073_Set_RefParamON.txt)
[SDC11073_StateEvent_RefParamOFF.txt](https://github.com/user-attachments/files/15951244/SDC11073_StateEvent_RefParamOFF.txt)
[SDC11073_StateEvent_RefParamON.txt](https://github.com/user-attachments/files/15951245/SDC11073_StateEvent_RefParamON.txt)

### Expected Behavior

Subscription should be renewed. Used sdcX Reference Consumer works with all other libraries out there. 

### Python Version

3.11

### Operating system

Windows, Linux

### Sdc11073 Version

2.0.1

### Participation

- [ ] I am willing to submit a pull request to fix this bug.

**Comment by deichmab-draeger** [comment]
It turned out to be a certificate problem in environment, no bug.
