### ISSUE TITLE
Subscribe to action metrics on the SDC provider side

### ISSUE THREAD

**Issue by weberja** [Draegerwerk/sdc11073#41]
For a master thesis, I want to implement an SDC-Serial-Port-Bridge in python. To achieve this, I want to subscribe to updates on the metrics, especially the action metrics. In my search in through the source code, I couldn't find an example for my problem.

After I created the `SdcDevice` how do I subscribe to action metrics. All other metrics I know how to subscribe to on the provider/device side.
```python
sdcDevice = SdcDevice(ws_discovery=myDiscovery,
                          my_uuid=my_uuid,
                          model=dpwsModel,
                          device=dpwsDevice,
                          deviceMdibContainer=my_mdib)
    # start the local device and make it discoverable
    sdcDevice.startAll()
```

Thanks for your help!

**Comment by ldeichmann** [comment]
Hi,

can you elaborate what you mean by `action metrics`? I've never heard that term before.

Additionally, please clarify what you're trying to do here. You started a provider, that much I get, but what kind of subscription are you talking about?  Do you want to subscribe to it over a network connection using a consumer, or are you trying to get access to the data within your provider implementation? Your snippet, which is just copied from the example verbatim, doesn't help me understand your scenario.

Thanks
Lukas

**Comment by weberja** [comment]
Hi,

Thanks for the replay. I was a bit unclear. Sorry.
I see now that I used the wrong term `action metric`. Let me provide you with the scenario, so it helps clarify what I try to do.

I create with sdc11073 an SDC Provider from an XML. Basically, I used the code from the tutorial provider and snippets from tests. The XML describe `SetStringOperationDescriptor`, `SetValueOperationDescriptor` and `ActivateOperationDescriptor`. Then i create the `Mdib`, `DPWS Model`, `DPWS Device`. After this, I create the `SdcDevice` and start it.

```python
#...

wsd = sdc.wsdiscovery.WSDiscoveryWhitelist([ip])
wsd.start()

cwd = os.path.dirname(__file__)
mdib_path = os.path.join(cwd, 'prosim_8_provider.xml')
self._mdib = sdc.mdib.DeviceMdibContainer.fromMdibFile(mdib_path)

dpws_model = sdc.pysoap.soapenvelope.DPWSThisModel(manufacturer='Fluke Biomedical', manufacturerUrl='fluke.com', modelName='ProSim8', modelNumber='8', modelUrl='', presentationUrl='')
dpws_device = sdc.pysoap.soapenvelope.DPWSThisDevice(friendlyName='Vitalsimulator', serialNumber='22222', firmwareVersion='1.0')

#...

sdc_device = SdcDevice(wsd, self.uuid, dpws_model, dpws_device, self._mdib, sslContext=None)
sdc_device.startAll()

#...
```

So, now I want to 'subscribe' an Observable, so the Provider is notified when an `SdcClient` active an `ActivationOperation`.

In the tutorial, examples and tests, I find how to subscribe to an observable of the `SdcDevice` class for `metrics` but I don't know how to do this for the `ActivationOperation`. For the `metrics` and so on, I used the following code. It was copied from the `reference_client.py`

```python
def onMetricUpdates(metricsbyhandle):
        print('onMetricUpdates', metricsbyhandle)
        for k, v in metricsbyhandle.items():
            metric_updates[k].append(v)

 

    def onAlertUpdates(alertsbyhandle):
        print('onAlertUpdates', alertsbyhandle)
        for k, v in alertsbyhandle.items():
            alert_updates[k].append(v)

 

observableproperties.bind(self._mdib, metricsByHandle=onMetricUpdates)
observableproperties.bind(self._mdib, alertByHandle=onAlertUpdates)
```

I hope this made it understandable. My goal is to know as the provider/device when an `ActivationOperation``was activated by a client.

Thanks for your time,
Jan

**Comment by deichmab-draeger** [comment]
Hi Jan, I uploaded an example test that shows how to connect your callback to operations.
It is located in tests/test-tutorial, test_operation_handler. It might not be on master yet. If not, check branch "example_operation_handler".

**Comment by weberja** [comment]
Hi Bernd,
thanks for the test and tutorial. It is really helpful.
