### ISSUE TITLE
Update list of properties for AbstractOperationDescriptorContainer class

### ISSUE THREAD

**Issue by Legion18z** [Draegerwerk/sdc11073#45]
Class **AbstractOperationDescriptorContainer** in sdc11073/mdib/descriptorcontainers.py have attribute **_props** being a list of attribute names of this class, but the attribute "AccessLevel" is not included in this list. This leads to the fact that method **_sortedContainerProperties** from file sdc11073/mdib/containerbase.py does not include attribute "AccessLevel" in the list of all container properties and method** _updateFromNode** does not read this attribute from the node. Therefore all operations in mdib have AccessLevel attribute with implied value = "Usr"

**Comment by deichmab-draeger** [comment]
solved in version 1.1.3
