### ISSUE TITLE
Add version/release tags and add releases to release page

### ISSUE THREAD

**Issue by maximilianpilz** [Draegerwerk/sdc11073#95]
Currently there are no releases on the repositories main page and the repository has no tags, but there are already multiple versions of sdc11073 released on pypi.

Although it is possible to associate a given whl file from pypi with a revision on GitHub through the information in the whl file itself, there is currently no reliable way of checking out the releases by only looking at the repository.

It would be nice and helpful to have the respective revisions associated with a version/release through git tags as well as to have releases on https://github.com/Draegerwerk/sdc11073/releases .

**Comment by leon1995** [comment]
will be done in #106
